### ISSUE TITLE
Deyerlendirme

### ISSUE THREAD

**Issue by samirkarimov** [Orxan223/PragmatechFrontendProject#4]
7/10 olaraq deyerlendirirem onu da menim yazdigim kodlardan cox istifade etdiyin ucun. amma cox daha gozel yazabileceyine eminem

**Comment by Orxan223** [comment]
Cox sag olun mellim , meslehetlere gore . InALLAH daha cox calisacam 

  
>Вторник, 8 декабря 2020, 9:27 +03:00 от Samir Karimov <notifications@github.com>:
> 
> 
>7/10 olaraq deyerlendirirem onu da menim yazdigim kodlardan cox istifade etdiyin ucun. amma cox daha gozel yazabileceyine eminem
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Or Xan
